<?php
	$lang = array(
		"title" => "Welcome to seralance",
		"home" => "Home",
		"howitworks" => "how it works?",
		"whatwoweoffer" => "what do we offer?",
		"aboutus" => "about us",
		"contactus" =>"contact us",
		"FAQ"=>"FAQ",
        "policy"=> "policy",
		"signin" => "sign in",
        "join"=> "join",
		"language" => "language",
		"provider"=>"service provider",
		"seeker"=>"service seeker",
		"Hsp"=>"Hire service provider",
		"Ap"=>"Announce Project",
		"Tra"=>"Transaction",
		"lang_en" => "English",
		"lang_am"=>"አማርኛ",
		"project"=>"project",
		"Notification"=>"Notification",
		"Message"=>"Message",
		"dispute"=>"dispute",
	);
?>